# Shell variables
# Generated by 'wal'
wallpaper='/home/bn/Pictures/wallpapers/Lofi-Room.png'

# Special
background='#131216'
foreground='#c6cddc'
cursor='#c6cddc'

# Colors
color0='#131216'
color1='#BDA16E'
color2='#64759C'
color3='#7488B0'
color4='#6A9DCD'
color5='#9399AF'
color6='#DEC6AE'
color7='#c6cddc'
color8='#8a8f9a'
color9='#BDA16E'
color10='#64759C'
color11='#7488B0'
color12='#6A9DCD'
color13='#9399AF'
color14='#DEC6AE'
color15='#c6cddc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
