--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bn/Pictures/wallpapers/Lofi-Room.png"

-- Special
background="#131216"
foreground="#c6cddc"
cursor="#c6cddc"

-- Colors
color0="#131216"
color1="#BDA16E"
color2="#64759C"
color3="#7488B0"
color4="#6A9DCD"
color5="#9399AF"
color6="#DEC6AE"
color7="#c6cddc"
color8="#8a8f9a"
color9="#BDA16E"
color10="#64759C"
color11="#7488B0"
color12="#6A9DCD"
color13="#9399AF"
color14="#DEC6AE"
color15="#c6cddc"
